### ISSUE TITLE
little bug about loss.py

### ISSUE THREAD

**Issue by FlowEternal** [motokimura/yolo_v1_pytorch#1]
pred_xyxy[:,  :2] = pred[:, 2]/float(S) - 0.5 * pred[:, 2:4] 
pred_xyxy[:, 2:4] = pred[:, 2]/float(S) + 0.5 * pred[:, 2:4]

**should be changed to** 
pred_xyxy[:,  :2] = pred[:, :2]/float(S) - 0.5 * pred[:, 2:4]
pred_xyxy[:, 2:4] = pred[:, :2]/float(S) + 0.5 * pred[:, 2:4]

and also for target_xyxy

**Comment by motokimura** [comment]
Thank you for reporting.
This has been solved in PR https://github.com/motokimura/yolo_v1_pytorch/pull/2 by nuka137.
