### ISSUE TITLE
couldn't load

### ISSUE THREAD

**Issue by HonestyBrave** [motokimura/yolo_v1_pytorch#5]
hi, when I run your code, I counter the problem, as follows the show, could you give me help?:
![image](https://user-images.githubusercontent.com/16200506/102895257-5adf3b00-449f-11eb-81cd-b2fdd4442185.png)

**Comment by HonestyBrave** [comment]
the "weights/darknet/model_best.pth.tar" is download from “http://datasets.lids.mit.edu/fastdepth/imagenet/results/imagenet.arch=mobilenet.lr=0.1.bs=256”
where could download your repositories pre-trained model?

**Comment by motokimura** [comment]
Hi, thanks for your interest.
Unfortunately pre-trained weight is not provided (I removed it accidentally).

**Comment by HonestyBrave** [comment]
thankyou for your reply,
So,  If i want to use the "train_yolov.py", I only to training the model by myself?

**Comment by motokimura** [comment]
Yes. You can use `train_darknet.py` script.
