### ISSUE TITLE
full connect

### ISSUE THREAD

**Issue by HonestyBrave** [motokimura/yolo_v1_pytorch#6]
hi, motokimura,
   i have a question about "_make_fc_layers" in "darknet.py", the yolo author is training darknet in Imagenet, the data classes is about 1000, but we are training in voc data set, the classes is about 20, so, the below picture red box wether change to 20?
![image](https://user-images.githubusercontent.com/16200506/103540638-ff687080-4ed4-11eb-8892-02db00d53eea.png)

**Comment by motokimura** [comment]
Hi, It should be 1,000.

After pre-trained Darknet on ImageNet (with 1,000 classes), only the convolution layers (layers except for the FC-layer) are passed to YOLO model as you can see in the implementation below. 
https://github.com/motokimura/yolo_v1_pytorch/blob/c3e60d7abdb6a36c472e4dae55ed696dfc08dd43/train_yolo.py#L79

In YOLO model, [a new FC-layer](https://github.com/motokimura/yolo_v1_pytorch/blob/master/yolo_v1.py#L54) is defined and it has 20 classes.

**Comment by HonestyBrave** [comment]
> Hi, It should be 1,000.
> 
> After pre-trained Darknet on ImageNet (with 1,000 classes), only the convolution layers (layers except for the FC-layer) are passed to YOLO model as you can see in the implementation below.
> https://github.com/motokimura/yolo_v1_pytorch/blob/c3e60d7abdb6a36c472e4dae55ed696dfc08dd43/train_yolo.py#L79
> 
> In YOLO model, [a new FC-layer](https://github.com/motokimura/yolo_v1_pytorch/blob/master/yolo_v1.py#L54) is defined and it has 20 classes.

**Comment by HonestyBrave** [comment]
Hi, thank you very much,
 it's me didn't understand completely, I print the model. features find is only have convolution layers, thank you!

**Comment by HonestyBrave** [comment]
But I confusion, when we training the model in VOC data sets, using the "train_darknet.py", the function of "_make_fc_layers" in "darknet.py" shouldn't change to 20? (because I understand, we training in VOC data sets, not in ImageNet data sets, that only 20 classes, not 1000), it's somewhere I didn't understand? could you give me a more explanation? thank you

**Comment by motokimura** [comment]
train_darknet.py has nothing to with VOC. It should run with ImageNet dataset because Darknet is firstly pre-trained on ImageNet as written in the original YOLO paper.

After pre-trained Darket on ImageNet, its feature extraction part (convolution layers) and YOLO head FC-layer are further fine-tuned on VOC dataset.

Maybe I should have prepared README explaining the procedure but I did not have enough time..

**Comment by HonestyBrave** [comment]
OK, I have understood, thank you very much!
